server:
  port: 9009
spring:
  application:
    name: social-sms
  rabbitmq:
    host: 192.168.1.106
aliyun:
  sms:
    accessKeyId: LTAI4FffwhQdPR72c3znGFnU
    accessKeySecret: n5REDHpaCBH973rpSpBjQr3EXFIFwD
    template_code: SMS_184115236
    sign_name: social