server:
  port: 9006
spring:
  application:
    name: social-spit
  data:
    mongodb:
      host: 192.168.1.106
      database: split
  redis:
    host: 192.168.1.106
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.106:6868/eureka/
  instance:
    prefer-ip-address: true # 注册服务的时候使用ip地址，ip地址从host里面找