server:
  port: 9007
spring:
  application:
    name: social-search
  data:
    elasticsearch:
      cluster-nodes: 192.168.1.106:9300 # 集群模式下用逗号分开
      cluster-name: docker-cluster
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.106:6868/eureka/
  instance:
    prefer-ip-address: true # 注册服务的时候使用ip地址，ip地址从host里面找